/**
 *  @file COMdsPICunusedISRs.c
 *  @brief This module implements interrupt service routines for the interrupts that are not used.
 *
 *  @date 22Nov2006
 *  @author Vamshi Gangumalla
 *
 *  @par <b> Description: </b>
 *     - This Interrupt Service Routine services the hardware interrupts
 *
 *  @par <b> Table of Contents: </b>
 *     The following functions are defined in this file:
 *     - v_OscillatorFail
 *     - v_AddressError
 *     - v_StackError
 *
 *  @par <b> Change History: </b> <BR>
 *     <table>
 *        <tr><td> <i> Date  <td> Release <td> Author <td> Description </i>
 *        <tr><td> 22Nov2006 <td> <center>Draft</center>   <td> <center>VG</center> <td> Initial Draft
 *        <tr><td> 27Mar2008 <td>   <center>"</center>     <td> <center>JD</center> <td> ADHR111
 *        <tr><td> 17Sep2008 <td>   <center>"</center>     <td> <center>JD</center> <td> ADHR259
 *        <tr><td> 23Sep2008 <td>  <center> 1.0 </center>   <td> <center>JD</center> <td> Baseline Release
 *        <tr><td> 30Oct2008 <td>  <center> 1.1 </center>   <td> <center>YC</center> <td> ADHR281: PR_CR_068
 *        <tr><td> 10Dec2008 <td>  <center> 1.2 </center>   <td> <center>JD</center> <td> ADHR280: PR_LLR_056
 *        <tr><td> 24Jun2009 <td>  <center> 1.3 </center>   <td> <center>JD</center> <td> ADHR334
 *  </table>
 *  <BR>
 *
 *  @note $Id: COMdsPICunusedISRs.c 6413 2009-07-13 15:49:58Z jayd $ <BR>
 *  @note <i> All rights reserved.  Copyright 2008.  Archangel Systems, Inc. </i> <BR>
 */

/**************  Include Files  ************************/
#include "COMdsPICunusedISRs.h"

/**
 * @brief This Interrupt service routine serves the interrupt call.
 *
 * @par <b> Detailed Description: </b>
 *      This function is called when a trap interrupt is generated by an address error.
 *      This function executes an infinite loop in order to avoid system output data corruption.
 *
 * @author Vamshi Gangumalla
 *
 * @par <b> Requirement(s) Implemented: </b> <BR>
 *       REL.0135.S.COM.10.005 \n
 *
 * @par <b> Parameters: </b> <br>
 *    <i> None </i> (void)
 */


void v_AddressError ( void )
{
   /* Enter an infinite loop to retain program flow control in order to avoid system output data corruption. */
   while ( ONE )
   { }
   return; /** @return \a None (void) */
}
/* End of the ISR. */

/**
 * @brief This Interrupt service routine serves the interrupt call.
 *
 * @par <b> Detailed Description: </b>
 *       This ISR is called when a trap interrupt is generated by an oscillator failure or a PLL lock failure.
 *       As clock switching and clock monitoring actions are disabled in the configuration bits, this ISR shall be entered
 *       under the following 2 conditions and the mentioned actions shall be taken:
 *       1. When PLL disengagement is reported.
 *       There is a silicon error present in the DSPIC6012A chip which causes PLL disengagement to be misreported
 *       during run time even if the PLL mechanism is working correctly. After entering this ISR the status of  the LOCK bit in the
 *       OSSCON (oscillator configuration) register is checked. If this bit is clear it indicates that a PLL lock disengagement
 *       has been falsely reported. To overcome this false alarm the system trap is exited without any action.
 *       2. If at power on boot the clock set up time exceeds the FSCM (fail safe clock monitoring) delay
 *       The FSCM delay is applied only when clock switching and monitoring is enabled. In case of this design the clock switching
 *       and monitoring is disabled, hence in case of the clock set up time exceeding the FSCM delay program control is
 *       transferred to this ISR. A processor software reset action shall be performed if there is no problem with the
 *       PLL lock status bit and only the non active FSCM delay is exceeded.
 *       Note: An actual clock failure shall be handled at the system level where a perceptible loss of computing power will
 *       result in loss of communication detectable by other subsystems or by assertion of the fault line.
 *
 * @author Jayendra Dabhade
 *
 * @par <b> Requirement(s) Implemented: </b> <BR>
 *       REL.0135.S.COM.10.004 \n
 *
 * @par <b> Parameters: </b> <br>
 *    <i> None </i> (void)
 */

void v_OscillatorFail ( void )
{
  /* Check the status of the PLL lock  */
  if ( OSCCONbits.LOCK == CLEAR )
  {
     /* Since the Fail safe clock monitor mechanism is not enabled, only a misreported PLL lock failure shall cause the
        program control to be transferred to this ISR. As per errata suggestion, do not take any action and just exit the ISR */
  }
  else
  {
     /* However if the PLL lock is engaged and  this ISR is entered it implies that since FCSM capability has been disabled,
        at boot a clock synchronization failure is reported. A software reset instruction needs to be included to reset
        the pprocessor.*/
     __asm__(" reset ") ;
  }

   return;/** @return \a None (void) */
}
/* End of the ISR. */

/**
 * @brief This Interrupt service routine serves the interrupt call.
 *
 * @par <b> Detailed Description: </b>
 *      This function is called when a trap interrupt is generated by an address error.
 *      This function executes an infinite loop in order to avoid system output data corruption.
 *
 * @author Vamshi Gangumalla
 *
 * @par <b> Requirement(s) Implemented: </b> <BR>
         REL.0135.S.COM.10.006 \n
 *
 *
 * @par <b> Parameters: </b> <br>
 *    <i> None </i> (void)
 */
void v_StackError ( void )
{
   /* Enter an infinite loop to retain program flow control in order to avoid system output data corruption. */
   while( ONE )
   { }
   return;/** @return \a None (void) */
}
/* End of the ISR. */


